#!/usr/bin/env python

int_bits  = 31
frac_bits = 31
flag_bits = 2

if __name__ == "__main__":
    print """/*********
 * This file is autogenerated by generate_base.py.
 * Please don't modify it manually.
 *********/

#ifndef base_h
#define base_h

typedef uint64_t fixed;

#define FIX_PRINTF_HEX "%%016llx"

#define FIX_FLAG_BITS %d
#define FIX_FRAC_BITS %d
#define FIX_INT_BITS  %d
#define FIX_BITS (8*sizeof(fixed))

#endif"""%(flag_bits, frac_bits, int_bits)
